# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
X = torch.rand((7,7))
X, X.shape

(tensor([[0.4915, 0.1587, 0.9859, 0.9806, 0.9493, 0.7304, 0.7711],
         [0.9554, 0.2475, 0.5574, 0.5372, 0.4210, 0.8318, 0.8370],
         [0.2703, 0.4210, 0.6581, 0.9618, 0.1208, 0.9039, 0.9280],
         [0.3933, 0.2141, 0.1750, 0.0966, 0.2837, 0.5385, 0.1232],
         [0.0249, 0.6844, 0.1115, 0.4277, 0.5755, 0.1065, 0.3111],
         [0.2552, 0.7552, 0.2179, 0.6560, 0.1920, 0.5623, 0.4527],
         [0.0354, 0.8160, 0.2526, 0.9063, 0.7026, 0.1108, 0.6003]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [20]:
# Create another random tensor
Y = torch.rand(size=(7,7))
# Perform matrix multiplication 
result = torch.multiply(X,Y)
result

tensor([[0.3324, 0.0799, 0.3279, 0.1681, 0.7821, 0.0618, 0.4045],
        [0.7404, 0.0673, 0.4127, 0.4992, 0.2485, 0.1039, 0.3254],
        [0.1831, 0.0654, 0.3683, 0.4733, 0.0013, 0.5659, 0.4342],
        [0.0127, 0.0132, 0.1348, 0.0130, 0.0281, 0.4257, 0.0216],
        [0.0168, 0.5405, 0.0701, 0.2261, 0.3532, 0.0704, 0.1546],
        [0.0459, 0.5471, 0.0748, 0.4602, 0.1686, 0.1379, 0.0447],
        [0.0119, 0.7455, 0.1839, 0.5013, 0.1059, 0.0094, 0.4119]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [32]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if (torch.cuda.is_available()) else 'cpu'
# Create two random tensors on GPU
x = torch.rand(2,3).to(device)
y = torch.rand(2,3).to(device)
x,y

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [44]:
# Perform matmul on tensor_A and tensor_B
tensorAB = torch.matmul(x,y.T)
tensorAB

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [47]:
# Find max
max_ = torch.max(tensorAB)
# Find min
min_ = torch.min(tensorAB)

min_,max_,tensorAB

(tensor(0.3647, device='cuda:0'),
 tensor(0.5617, device='cuda:0'),
 tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [48]:
# Find arg max
max_ = torch.argmax(tensorAB)

# Find arg min
min_ = torch.argmin(tensorAB)

min_,max_,tensorAB

(tensor(0, device='cuda:0'),
 tensor(3, device='cuda:0'),
 tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
x = torch.rand(size=(1,1,1,10))

# Remove single dimensions
x = x.squeeze()

# Print out tensors and their shapes
x ,x.shape

(tensor([[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]),
 torch.Size([1, 1, 10]))